services:
  identity-webapi:
    image: peo/identity-webapi:1.0
    build:
      context: .
      dockerfile: src/Peo.Identity.WebApi/Dockerfile

  gestao-conteudo-webapi:
    image: peo/gestao-conteudo-webapi:1.0
    build:
      context: .
      dockerfile: src/Peo.GestaoConteudo.WebApi/Dockerfile

  gestao-alunos-webapi:
    image: peo/gestao-alunos-webapi:1.0
    build:
      context: .
      dockerfile: src/Peo.GestaoAlunos.WebApi/Dockerfile

  faturamento-webapi:
    image: peo/faturamento-webapi:1.0
    build:
      context: .
      dockerfile: src/Peo.Faturamento.WebApi/Dockerfile

  web-bff:
    image: peo/web-bff:1.0
    build:
      context: .
      dockerfile: src/Peo.Web.Bff/Dockerfile

  web-spa:
    image: peo/web-spa:1.0
    build:
      context: .
      dockerfile: src/Peo.Web.Spa/Dockerfile