apiVersion: v1
kind: Secret
metadata:
  name: peo-secrets
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong!Passw0rd"

  JWT_KEY: "CHANGE_ME_PUT_YOUR_LONG_RANDOM_KEY_HERE"

  IDENTITY_SQL_CONN: "Server=peo-sqlserver,1433;Database=PeoIdentity;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True"
  GESTAO_CONTEUDO_SQL_CONN: "Server=peo-sqlserver,1433;Database=PeoGestaoConteudo;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True"
  GESTAO_ALUNOS_SQL_CONN: "Server=peo-sqlserver,1433;Database=PeoGestaoAlunos;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True"
  FATURAMENTO_SQL_CONN: "Server=peo-sqlserver,1433;Database=PeoFaturamento;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True"